export interface ITaskItemList {
    taskDetails:any, 
    users:any, 
    isMissing:any,
    getUser:any, 
    updateCommentCount:any, 
    userState:any, 
    closeObservation:any, 
    subTask:any, 
    positionTaskStates:any, 
    changePositionItem:any, 
    updatePositionTaskItem:any,
    checkedItem:any,
    togglePositionTask:any,
    setOnScrollDown:any,
    onScrollDown:any,
    userLog:any,
    setUserState:any,
    updatedAddUserTaskItem:any,
    showChat:any,
    setEditTask:any,
    setOnEditTask:any,
    setShowChat:any,
    setTaskToDelete:any,
    setIsTrashDelete:any,
    updateItemTaskFile:any,
    props: any,
};

export interface IUserLinkingList {
    userState: any,
    setUserState: any,
    signature: any,
    updatedAddUserTaskItem: any,
    getUser: any,
}